spring.application.name=tije-front
server.port=${FRONT_PORT:8081}
server.servlet.session.cookie.name=TIJEFRONTSESSION
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true

spring.mvc.view.prefix=/WEB-INF/vistas/
spring.mvc.view.suffix=.jsp

app.backend.url=${BACKEND_URL:http://localhost:8080}
