spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    clean-disabled: true
  jpa:
    show-sql: false

server:
  forward-headers-strategy: framework
  servlet:
    session:
      cookie:
        secure: true

app:
  seguridad:
    origen-frontend: ${FRONTEND_ORIGIN}
