spring.application.name=tije-back

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/tijetravel}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false